### ISSUE TITLE
Initial move animation isn't correct when the board flips in The Climb

### ISSUE THREAD

**Issue by jpnance** [marcusbuffett/chess-trainer-site#1]
When playing "The Climb", the hidden moves are automatically animated whenever we start a new puzzle. If we've changed colors from the previous puzzle (i.e. if we've flipped the board), the moves still animate relative to the old board orientation. Pressing the play button manually will show the correct animations but it'd be great to have the initial automatic animation be correct.

This doesn't seem to be an issue on "Visualization" because the moves don't get automatically animated when we go to a new puzzle.

**Comment by jpnance** [comment]
I forgot to note that this is in Firefox 95.0.1 on Ubuntu 21.10 but I've also noticed it in Firefox on my Mac.

**Comment by marcusbuffett** [comment]
dang, thought I had fixed this, I’ll look into it

**Comment by marcusbuffett** [comment]
This should be fixed now.

**Comment by marcusbuffett** [comment]
Oof, there's a new issue now. Sometimes the board doesn't get flipped... Got to figure out a better way to handle all this board and game state, it's a mess right now. Will try to get this fixed in the next couple days.

**Comment by marcusbuffett** [comment]
Alright, actually fixed now. Things aren't nearly as messy anymore, zustand ftw
