### ISSUE TITLE
Importing with username gives a bad request error

### ISSUE THREAD

**Issue by TBestLittleHelper** [marcusbuffett/chess-trainer-site#4]
https://chessmadra.com/openings
Example username : TBest

In the console log, (after expanding the uncaught a bit) you can find the following error : 

>response: "{\"error\":\"Json deserialize error: missing field `rating` at line 1 column 9084\"}"
​​responseText: "{\"error\":\"Json deserialize error: missing field `rating` at line 1 column 9084\"}"

**Comment by marcusbuffett** [comment]
Really appreciate the detailed report, hadn't considered games that were against anonymous users, didn't really know that was a thing. This should be fixed - deploy will take about ~20 minutes, then your username will work. Thanks!
