### ISSUE TITLE
Displayed lines are off by one

### ISSUE THREAD

**Issue by kenan-rhoton** [marcusbuffett/chess-trainer-site#6]
It's a minor issue, but when reviewing lines, the notation shows all moves except for your opponent's *last* move.

This may be related to the issue where, during editing, the move tree is also off by one (so when editing white moves, if I start with c4, it won't have the "1." in front of it, but my opponents first move will, for example "1. e5")

**Comment by marcusbuffett** [comment]
Ah good catch, and I had noticed the tree issue but forgot to address it before deploying. Will look into them

**Comment by marcusbuffett** [comment]
These should both be fixed now! Thanks for the report
